### PR TITLE
Add support for nice url rewriting via htaccess

### PR DESCRIPTION
**Pull request by jasonheecs**
**Description of the change**
Adds a .htaccess file into the container. To enable url rewriting, one can modify AllowOverride directive in the `dokuwiki-vhost.conf` file that is potentially mounted as a persistent volume.

**Benefits**

Enables one to turn on pretty permalinks easily by modifying a file that is mounted on the host machine.

**Possible drawbacks**

**Applicable issues**

#39 
**Additional information**

### CODE REVIEW

**Comment by svenssonaxel** [comment]
There is no need to set AllowOverride to All, and it is not recommended by Apache.

Also, IIUC this PR adds /opt/bitnami/dokuwiki/.htaccess but does not make it configurable through the permanent volume, which could be valuable in some cases.

Suggestion: Instead of /opt/bitnami/dokuwiki/.htaccess, rewrite rules could go into /bitnami/apache/conf/vhosts/dokuwiki-vhost.conf, inside the <Directory> block. The README would have to reflect that, and maybe the rewrite rules should be commented by default, as they are in the template /opt/bitnami/dokuwiki/.htaccess.dist.

This suggestion could be seen as a smaller change to gain at least the same benefit: Only the readme and the default for one of the config files need to change. In fact, using this technique it's already possible to turn on pretty permalinks by modifying a config file mounted on the host.

Something to consider: Is there any security or functionality risk in enabling the rewrite rules by default? If not, then doing so would make it possible to enable pretty permalinks through the application interface only, which would be more user friendly.

**Comment by juan131** [comment]
Hi @svenssonaxel 

I agree with you. We should try to avoid using **.htaccess** files since it's not recommend by Apache. You can include your custom rules by creating a file at **/opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf** with them. That file is included on the Apache configuration as you can check running the command below:

```
docker-compose exec dokuwiki grep "Include" /opt/bitnami/apache/conf/vhosts/dokuwiki-vhost.conf
  Include /opt/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf
```

> Something to consider: Is there any security or functionality risk in enabling the rewrite rules by default? 

What do you think about this solution? Enabling a boolean env. variable such as **ENABLE_PERMALINKS** that creates the proper htaccess rules when set to `true`

**Comment by svenssonaxel** [comment]
@juan131 

Right,`/bitnami/apache/conf/vhosts/htaccess/dokuwiki-htaccess.conf` might be a better place to put it.

I think having the rules always on would be preferable, since that would make it easier to configure nice urls - all you'd have to do is activating it through the admin GUI. I don't believe this brings on any security risk, but we should probably ask on the dokuwiki dev list first. Actually, maybe nice urls can even be turned on by default - it's probably more common to use them than not to, and I believe the need to configure the web server is the only reason why it's off by default.

The downside of creating the proper rules automatically depending on an environment variable, is that it could interfere with custom edits to the config files, and will add some unnecessary complexity. We could put the rules inside an <If> block that is conditional on the environment variable, but only if we need to due to some security concern.

**Comment by juan131** [comment]
Continuing discussion on https://github.com/bitnami/bitnami-docker-dokuwiki/issues/52

**Comment by khannurien** [comment]
Hi, is there any news regarding URL rewriting?

**Comment by juan131** [comment]
Hi @khannurien 

As I mentioned at https://github.com/bitnami/bitnami-docker-dokuwiki/issues/52 we created an internal task in our backlog to work on this feature but we didn't have time to work on it yet. 

Thanks so much for your consideration and patience. We'll notify you as soon as there are more news.

**Comment by marcosbc** [comment]
Hi all, just wanted to let you know that we have just released DokuWiki `20200729.0.0-debian-10-r6` which enables nice/friendly URLs by default.

Since it has already been added, I'm proceeding to close this PR.

**Pull request closed without merging**
